export const countries = [
  { id: 1, name: 'Paraguay' },
  { id: 2, name: 'Estados Unidos' },
  { id: 3, name: 'China' },
  { id: 4, name: 'India' },
  { id: 5, name: 'Indonesia' },
  { id: 6, name: 'Brasil' },
  { id: 7, name: 'Pakistán' },
  { id: 8, name: 'Nigeria' },
  { id: 9, name: 'Bangladés' },
  { id: 10, name: 'Rusia' },
  { id: 11, name: 'México' },
  { id: 12, name: 'Japón' },
  { id: 13, name: 'Etiopía' },
  { id: 14, name: 'Filipinas' },
  { id: 15, name: 'Egipto' },
  { id: 16, name: 'Vietnam' },
  { id: 17, name: 'República Democrática del Congo' },
  { id: 18, name: 'Turquía' },
  { id: 19, name: 'Irán' },
  { id: 20, name: 'Alemania' },
  { id: 21, name: 'Tailandia' },
  { id: 22, name: 'Reino Unido' },
  { id: 23, name: 'Francia' },
  { id: 24, name: 'Italia' },
  { id: 25, name: 'Tanzania' },
  { id: 26, name: 'Sudáfrica' },
  { id: 27, name: 'Myanmar' },
  { id: 28, name: 'Kenia' },
  { id: 29, name: 'Corea del Sur' },
  { id: 30, name: 'Colombia' },
  { id: 31, name: 'España' },
  { id: 32, name: 'Uganda' },
  { id: 33, name: 'Argentina' },
  { id: 34, name: 'Argelia' },
  { id: 35, name: 'Sudán' },
  { id: 36, name: 'Ucrania' },
  { id: 37, name: 'Irak' },
  { id: 38, name: 'Afganistán' },
  { id: 39, name: 'Polonia' },
  { id: 40, name: 'Canadá' },
  { id: 41, name: 'Marruecos' },
  { id: 42, name: 'Arabia Saudita' },
  { id: 43, name: 'Uzbekistán' },
  { id: 44, name: 'Perú' },
  { id: 45, name: 'Angola' },
  { id: 46, name: 'Malasia' },
  { id: 47, name: 'Mozambique' },
  { id: 48, name: 'Ghana' },
  { id: 49, name: 'Yemen' },
  { id: 50, name: 'Nepal' },
  { id: 51, name: 'Venezuela' },
  { id: 52, name: 'Madagascar' },
  { id: 53, name: 'Camerún' },
  { id: 54, name: "Costa de Marfil" },
  { id: 55, name: 'Corea del Norte' },
  { id: 56, name: 'Australia' },
  { id: 57, name: 'Níger' },
  { id: 58, name: 'Taiwán' },
  { id: 59, name: 'Sri Lanka' },
  { id: 60, name: 'Burkina Faso' },
  { id: 61, name: 'Mali' },
  { id: 62, name: 'Rumanía' },
  { id: 63, name: 'Malawi' },
  { id: 64, name: 'Chile' },
  { id: 65, name: 'Kazajistán' },
  { id: 66, name: 'Zambia' },
  { id: 67, name: 'Guatemala' },
  { id: 68, name: 'Ecuador' },
  { id: 69, name: 'Syria' },
  { id: 70, name: 'Paises Bajos' },
]
