export const countries = [
  { value: 1, label: 'Paraguay' },
  { value: 2, label: 'Estados Unidos' },
  { value: 3, label: 'China' },
  { value: 4, label: 'India' },
  { value: 5, label: 'Indonesia' },
  { value: 6, label: 'Brasil' },
  { value: 7, label: 'Pakistán' },
  { value: 8, label: 'Nigeria' },
  { value: 9, label: 'Bangladés' },
  { value: 10, label: 'Rusia' },
  { value: 11, label: 'México' },
  { value: 12, label: 'Japón' },
  { value: 13, label: 'Etiopía' },
  { value: 14, label: 'Filipinas' },
  { value: 15, label: 'Egipto' },
  { value: 16, label: 'Vietnam' },
  { value: 17, label: 'República Democrática del Congo' },
  { value: 18, label: 'Turquía' },
  { value: 19, label: 'Irán' },
  { value: 20, label: 'Alemania' },
  { value: 21, label: 'Tailandia' },
  { value: 22, label: 'Reino Unido' },
  { value: 23, label: 'Francia' },
  { value: 24, label: 'Italia' },
  { value: 25, label: 'Tanzania' },
  { value: 26, label: 'Sudáfrica' },
  { value: 27, label: 'Myanmar' },
  { value: 28, label: 'Kenia' },
  { value: 29, label: 'Corea del Sur' },
  { value: 30, label: 'Colombia' },
  { value: 31, label: 'España' },
  { value: 32, label: 'Uganda' },
  { value: 33, label: 'Argentina' },
  { value: 34, label: 'Argelia' },
  { value: 35, label: 'Sudán' },
  { value: 36, label: 'Ucrania' },
  { value: 37, label: 'Irak' },
  { value: 38, label: 'Afganistán' },
  { value: 39, label: 'Polonia' },
  { value: 40, label: 'Canadá' },
  { value: 41, label: 'Marruecos' },
  { value: 42, label: 'Arabia Saudita' },
  { value: 43, label: 'Uzbekistán' },
  { value: 44, label: 'Perú' },
  { value: 45, label: 'Angola' },
  { value: 46, label: 'Malasia' },
  { value: 47, label: 'Mozambique' },
  { value: 48, label: 'Ghana' },
  { value: 49, label: 'Yemen' },
  { value: 50, label: 'Nepal' },
  { value: 51, label: 'Venezuela' },
  { value: 52, label: 'Madagascar' },
  { value: 53, label: 'Camerún' },
  { value: 54, label: 'Costa de Marfil' },
  { value: 55, label: 'Corea del Norte' },
  { value: 56, label: 'Australia' },
  { value: 57, label: 'Níger' },
  { value: 58, label: 'Taiwán' },
  { value: 59, label: 'Sri Lanka' },
  { value: 60, label: 'Burkina Faso' },
  { value: 61, label: 'Mali' },
  { value: 62, label: 'Rumanía' },
  { value: 63, label: 'Malawi' },
  { value: 64, label: 'Chile' },
  { value: 65, label: 'Kazajistán' },
  { value: 66, label: 'Zambia' },
  { value: 67, label: 'Guatemala' },
  { value: 68, label: 'Ecuador' },
  { value: 69, label: 'Syria' },
  { value: 70, label: 'Paises Bajos' },
];
